### ISSUE TITLE
[Bug] Not working with ESM modules

### ISSUE THREAD

**Issue by bhvngt** [LeDDGroup/typescript-transform-paths#134]
I am trying this out with my `esm` module with following configuration

#### **`tsconfig.tsnode.json`**
```json
{
	"include": ["src/**/*", "tests/**/*"],
	"exclude": ["node_modules/*", "coverage/*"],
	"ts-node": {
		"transpileOnly": true,
		"require": ["typescript-transform-paths/register"]
	},
	"compilerOptions": {
		"target": "esnext",
		"module": "esnext",
		"lib": ["dom", "esnext"],
		"moduleResolution": "node",
		"strict": true,
		"forceConsistentCasingInFileNames": true,
		"importsNotUsedAsValues": "error",
		"incremental": true,
		"types": ["node", "jest"],
                "baseUrl": ".",
		"paths": {
			"$src/*": ["./src/*"]
		},
		"isolatedModules": false,
		"plugins": [
			{ "transform": "typescript-transform-paths" },
			{ "transform": "typescript-transform-paths", "afterDeclarations": true }
		]
	}
}
```
#### **`package.json`**
```json
{
...
"type": "module"
...
}
```
#### **`b.ts`**
```ts
export const b: string = "Hello World!"
```
#### **`a.ts`**
```ts
import {b} from "$src/b"

console.log(b);
```

`TS_NODE_PROJECT=tsconfig.tsnode.json node --loader ts-node/esm --es-module-specifier-resolution=node src/a.ts` throws 
```
/projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:774
  throw new ERR_MODULE_NOT_FOUND(packageName, fileURLToPath(base));
        ^
CustomError: Cannot find package '$src' imported from /projects/libs/domain/src/a.ts
    at packageResolve (/projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:774:9)
    at moduleResolve (/projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:815:18)
    at Object.defaultResolve (/projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/dist-raw/node-esm-resolve-implementation.js:929:11)
    at /projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/src/esm.ts:68:38
    at Generator.next (<anonymous>)
    at /projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/dist/esm.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/dist/esm.js:4:12)
    at resolve (/projects/common/temp/node_modules/.pnpm/ts-node@10.2.1_c780171742f6906a053a603dfa210a4e/node_modules/ts-node/dist/esm.js:32:16)
    at Loader.resolve (node:internal/modules/esm/loader:89:40)
```

if I change import in `a.ts` to relative path `import {b} from "./b"`, it works with the same command.

When used with `commonjs` works by changing `module` to `commonjs` under `tsconfig` and removing `"type": "module"` under `package.json` with cli `TS_NODE_PROJECT=tsconfig.tsnode.json ts-node src/a.ts`

**Comment by nonara** [comment]
Thanks for the report! I had a look at the `ts-node` source, and I think I know what's going on. Will be looking into it.

**Comment by bhvngt** [comment]
Thanks @nonara. That was really quick. Appreciate your help.

**Comment by bhvngt** [comment]
Since TypeStrong/ts-node#1439 has been merged, is there any other blocker to this issue? 

Appreciate your effort and contribution @nonara.

**Comment by nonara** [comment]
No blocker, per se, but things have been incredibly busy. This is rolled into the upcoming new major release, which has a lot of changes. I'm working on wrapping that up, and hope to have it out soon!

**Comment by nonara** [comment]
Feature is finished and working! You can have a look here:

- #145

Shouldn't be too long before we have a release ready.

**Comment by bhvngt** [comment]
Thanks @nonara. Will check this out.

**Comment by xpuu** [comment]
Hi @nonara, thanks for this useful lib. I'm looking forward to v4 release. I tried to test it in the meantime with the v4 branch, but without much success. Probably just me being tired and stupid. @bhvngt  Did that work for you?

**Comment by bhvngt** [comment]
@xpuu I have moved on to using other libraries. I am hoping that when typescript releases their implementation supporting [self-referencing package](https://github.com/microsoft/TypeScript/issues/38675), we may have a more [standard compliant](https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name) way of handling this use case - moving away from relative imports.

**Comment by nonara** [comment]
@xpuu Thanks for the kind words! v4 is close, but there were a few issues.

As many can understand in these unusual times, circumstances took me away from being able to do open source work for awhile. I'm very much looking forward to wrapping v4 and hoping to soon, but I need to get things stable first.

I've been swamped on contract work, but I've just launched a firm, which will help me offload some of the work and eventually free me up to work on open source again. 

I do hope to be able to get this wrapped on one of the upcoming weekends, however.

**Comment by xpuu** [comment]
@nonara Just so you know, I'm covered for now (solved this using some weird custom loader). Your message about your current workload really resonates with me. Good luck!

**Comment by halfbakedsneed** [comment]
Hey @nonara, is there anything we can do to help with the release of v4? Would love to see it released as this transformer is the only way I've managed to handle NX path mappings at runtime without using esbuild. No ESM support is the only drawback.

**Comment by danielpza** [comment]
Hey everyone, until v4 is ready, if you make a PR we can review it and try to merge it to v3

**Comment by nonara** [comment]
@halfbakedsneed I appreciate the offer!

ESM and replicating node's require behaviour is a tricky problem, but this is definitely long overdue. 

I finally got some time to set aside and revamp OSS. I just finished a rewrite of `ts-patch` and `ts-expose-internals`.

I have to do a few quick PR and issue closes for `node-html-markdown`, which should be quick, then I'll get this thing wrapped and pushed out.

If you do want to help, feel free to have a look at the open branch and let me know if you think there's an area you feel you can take on. If memory serves, it was largely a matter of finishing tests, but I'll have to check again.

**Comment by gralony** [comment]
Hey any update on this?

**Comment by danielpza** [comment]
This might be a configuration issue. Can you provide a reproduction case using this [link](https://stackblitz.com/github/leddgroup/typescript-transform-paths/tree/master/examples/basic)

[This example](https://github.com/LeDDGroup/typescript-transform-paths/tree/master/examples/basic) is using ESM and it's working for me

**Comment by danielpza** [comment]
Closing to keep the backlog clean. If you are still having this issue, please provide a reproduction example using [this link](https://stackblitz.com/github/leddgroup/typescript-transform-paths/tree/master/examples/basic)
